# Generated by Django 5.1.2 on 2024-11-01 16:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='evennt_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
