# Generated by Django 5.1.2 on 2024-11-01 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_event_evennt_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='content',
            new_name='event_detail',
        ),
    ]
