# Generated by Django 5.1.2 on 2024-11-01 16:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_alter_event_evennt_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='evennt_date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
