# Generated by Django 5.1.2 on 2024-11-05 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_alter_event_evennt_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='catagory',
            field=models.CharField(max_length=50),
        ),
    ]
