# Generated by Django 5.1.2 on 2024-11-05 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_alter_event_catagory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='catagory',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='evennt_date',
            new_name='event_date',
        ),
    ]
